# Prometheus Configuration for Document RAG System
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # OpenTelemetry Collector metrics
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']
    scrape_interval: 10s
    metrics_path: /metrics

  # Document RAG application metrics (if exposed directly)
  - job_name: 'document-rag-backend'
    static_configs:
      - targets: ['host.docker.internal:8001']
    scrape_interval: 15s
    metrics_path: /metrics
    scrape_timeout: 10s

  - job_name: 'document-rag-api'
    static_configs:
      - targets: ['host.docker.internal:8000']
    scrape_interval: 15s
    metrics_path: /metrics
    scrape_timeout: 10s

  # Qdrant metrics (external instance)
  - job_name: 'qdrant'
    static_configs:
      - targets: ['host.docker.internal:6333']
    scrape_interval: 30s
    metrics_path: /metrics